haxelib git haxefmod https://github.com/Tanz0rz/haxe-fmod.git
haxelib install flixel 4.7.0
haxelib install openfl 8.9.6
haxelib install lime 7.6.3
haxelib install flixel-addons 2.9.0
haxelib install flixel-tools 1.4.4
haxelib install flixel-ui 2.3.2
haxelib git bitlytics https://github.com/bitDecayGames/Bitlytics.git
haxelib git textpop https://github.com/bitDecayGames/text-pop.git
haxelib git flixelutils https://github.com/bitDecayGames/flixel-utils.git
