/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Level1:String = "event:/Music/Level1";
    public static inline var Level2:String = "event:/Music/Level2";
    public static inline var Level3:String = "event:/Music/Level3";
    public static inline var Tutorial:String = "event:/Music/Tutorial";
}

class FmodSFX {
    public static inline var ComboLost:String = "event:/SFX/Combo/ComboLost";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var Metranome130:String = "event:/SFX/Metranome/Metranome130";
    public static inline var Metranome135:String = "event:/SFX/Metranome/Metranome135";
    public static inline var Rewind:String = "event:/SFX/Rewind/Rewind";
}
